[package]
name = "schoolbot"
version = "0.1.0"
authors = ["sinnrrr <dimasoltusyuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
